"""CARLA 紧急避障场景的集中配置。"""

HOST = "localhost"
PORT = 2000
MAP_NAME = "Town10HD_Opt"
CLIENT_TIMEOUT = 120.0
FIXED_DELTA_SECONDS = 0.05
SIM_SECONDS = 90.0

INITIAL_GAP = 48.0
LEAD_BRAKE_TIME = 6.0
EGO_TARGET_SPEED = 15.5
LEAD_TARGET_SPEED = 13.0

TTC_AVOID_THRESHOLD = 3.6 # 右侧目标预测 TTC 风险阈值
LANE_CLEAR_FRONT = 45.0 # 跟踪路线前方目标搜索基础距离

# ========= 前向/右侧感知增强参数 =========
FRONT_LANE_ADJACENT_THRESHOLD = 1.2 # 前向候选保留的最大横向车道宽度比例
FRONT_TOP_K = 2 # 前向感知保留的最近车辆数量
FRONT_CONFLICT_LATERAL_MARGIN = 0.25 # 前车冲突横向包络额外安全边距（米）
FRONT_STEER_MAX_LATERAL_ACCEL = 3.8 # 前向转向最大横向加速度（m/s²），用于计算安全转向距离
FRONT_STEER_SAFE_DISTANCE = 3.0 # 前向转向安全距离（米），用于判断是否需要提前转向
FRONT_BRAKE_REACTION_TIME = 0.35
FRONT_BRAKE_MAX_DECEL = 7.0
FRONT_BRAKE_SAFE_DISTANCE = 2.0
FRONT_BRAKE_RELEASE_MARGIN = 5.0
FRONT_PLANNING_RETRY_SPEED_DROP = 5.0
RIGHT_CONFIRM_FRAMES = 3

LANE_CHANGE_LENGTH = 28.0
MPC_HORIZON_STEPS = 18
MPC_DT = 0.10
WHEEL_BASE = 2.85

TOWN10_START_SPAWN_INDEX = 141
TOWN10_ROUTE_STEP = 4.0
TOWN10_ROUTE_CLOSE_RADIUS = 8.0
TOWN10_ROUTE_MIN_POINTS_BEFORE_CLOSE = 80
TOWN10_ROUTE_SELF_CLOSE_MIN_SEPARATION = 55
TOWN10_ROUTE_CLOSE_HEADING_DEGREES = 25.0
TOWN10_SHORT_LOOP_BRANCH_OVERRIDES = { # (road_id, lane_id): step_index_override
    (5, -1): 795,
    (13, -2): 934,
    (20, -2): 875,
}
TOWN10_RIGHT_TURN_PREPARE_LANE_CHANGES = {
    (1, 1),
}
TOWN10_RIGHT_TURN_PREPARE_MAX_X = 36.0
TOWN10_RIGHT_TURN_PREPARE_HEADING_DEGREES = 180.0
TOWN10_RIGHT_TURN_PREPARE_HEADING_TOLERANCE = 15.0
ROUTE_COMPLETION_HOLD_SECONDS = 4.0

RIGHT_OBJECT_TTC_THRESHOLD = 5.0
RIGHT_OBJECT_DETECT_DISTANCE = 34.0
RIGHT_OBJECT_STOP_DISTANCE = 13.0
RIGHT_OBJECT_STOP_RELEASE_DISTANCE = 14.5
RIGHT_OBJECT_YIELD_SPEED = 3.0
RIGHT_OBJECT_LONGITUDINAL_MIN = -30.0
RIGHT_OBJECT_LONGITUDINAL_MAX = 12.0
RIGHT_OBJECT_LATERAL_MIN = -3.0
RIGHT_OBJECT_LATERAL_MAX = 20.0
RIGHT_OBJECT_TRIGGER_ROAD = 344
RIGHT_OBJECT_EXIT_ROAD = 20
RIGHT_OBJECT_TRIGGER_ROUTE_STEPS = 8  # 控制行人自行车开始运动
RIGHT_OBJECT_CLEAR_ROUTE_STEPS = 14
RIGHT_OBJECT_CROSSING_SPEED = 3.8
RIGHT_OBJECT_R344_ANCHOR_BACK_STEPS = 6
RIGHT_OBJECT_R344_RIGHT_OFFSET = 2.4
RIGHT_OBJECT_R344_START_FORWARD_OFFSET = -3.5  
RIGHT_OBJECT_R344_END_FORWARD_OFFSET = 42.0  

TRAFFIC_RANDOM_SEED = 20260602
BACKGROUND_VEHICLE_ROUTE_INDICES = (32, 54, 76, 96, 108)
BACKGROUND_VEHICLE_SPEED_MIN = 7.0
BACKGROUND_VEHICLE_SPEED_MAX = 8.8
BACKGROUND_VEHICLE_EGO_CLEARANCE = 18.0
BACKGROUND_BICYCLE_FORWARD_OFFSETS = (-1.5,)  
BACKGROUND_BICYCLE_RIGHT_OFFSETS = (4.6,)      
BACKGROUND_BICYCLE_END_FORWARD_OFFSET = 48.0  
BACKGROUND_BICYCLE_SPEED_MIN = 2.6
BACKGROUND_BICYCLE_SPEED_MAX = 4.3

RIGHT_PEDESTRIAN_FORWARD_OFFSETS = (-2.2, -2.9)  
RIGHT_PEDESTRIAN_RIGHT_OFFSETS = (3.0, 3.6)
RIGHT_PEDESTRIAN_END_FORWARD_OFFSET = 38.0  # 
RIGHT_PEDESTRIAN_SPEEDS = (2.3, 2.5)

SLOW_RIGHT_LANE_DISTANCE = 95.0  # 第二辆慢车出生点
SLOW_RIGHT_LANE_SPEED = 6.5 #第二辆慢车速度
SLOW_RIGHT_LANE_ROLE_NAME = "slow_right_lane_vehicle"

# ========= 传感器模拟参数 =========
SENSOR_NOISE_ENABLED = True
FRONT_DETECTION_RANGE = 80.0
SIDE_DETECTION_RANGE = 30.0
FRONT_FOV_HALF_ANGLE_DEG = 60.0
SIDE_FOV_HALF_ANGLE_DEG = 75.0
DISTANCE_STD = 0.5
SPEED_STD = 0.3
MISS_DETECTION_PROB = 0.05

# ========= 左侧传感器/侧向监测参数 =========
# 只用于显示和诊断，不参与前车避障决策。
LEFT_SENSOR_ENABLED = True
LEFT_SENSOR_LONGITUDINAL_BACK = 12.0
LEFT_SENSOR_LONGITUDINAL_FRONT = 22.0
LEFT_SENSOR_LATERAL_MIN = 0.4
LEFT_SENSOR_LATERAL_MAX = 4.8
LEFT_SENSOR_WARN_DISTANCE = 3.2
LEFT_SENSOR_DANGER_DISTANCE = 1.4
LEFT_SENSOR_TTC_THRESHOLD = 2.5

# 默认保持虚拟真值+噪声感知，避免雷达聚类改变已验证的控制演示。
RADAR_ENABLED = False
RADAR_RANGE = 80.0
RADAR_FOV_HORIZONTAL_DEG = 60.0
RADAR_FOV_VERTICAL_DEG = 15.0
RADAR_POINTS_PER_SECOND = 1500
RADAR_CLUSTER_RADIUS = 1.8
RADAR_MIN_POINTS_PER_CLUSTER = 3

DEBUG_DRAW_TRAJECTORY = True
DEBUG_DRAW_LOOKAHEAD_DISTANCE = 10.0
DEBUG_DRAW_TRAJECTORY_STEP = 4.0
DEBUG_DRAW_INTERVAL_FRAMES = 8
DEBUG_DRAW_LIFETIME = 0.45
DEBUG_DRAW_TRAJECTORY_DURATION = 3.0
DEBUG_DRAW_SELECTED_TRAJECTORY_ONLY = True
DEBUG_DRAW_MAX_ALTERNATIVE_TRAJECTORIES = 0

# ========= 传感器可视化参数 =========
DEBUG_DRAW_SENSOR_OVERLAY = True
